/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "ca-central-1",
    "aws_cognito_identity_pool_id": "ca-central-1:47ba7dae-5bd9-4855-a891-26b71fbb9a75",
    "aws_cognito_region": "ca-central-1",
    "aws_user_pools_id": "ca-central-1_gXOKopZTh",
    "aws_user_pools_web_client_id": "5qioecrb2lmquv3d5bh1dfskm4",
    "oauth": {}
};


export default awsmobile;
